### ISSUE TITLE
Enrich dataset obtained with CREW - ASPIS pipeline (EPIC: INCREASING INFORMATION CONTENT FOR RASAR)

### ISSUE THREAD

**Issue by Maddocent** [ontox-hu/aspis4j#9]
To enrich the current version of the CREW-ASPIS-chemicals-dataset (see https://github.com/ontox-hu/ontox-nlp-iris/blob/main/code/aspis_select_workflow.ipynb) we could do all or multiple of the following:

 - [ ] Connect compound data from CTD to CREW-ASPIS nodes
 - [ ] Rerun CREW on fulltext 
 - [ ] Refine Pubmed query to include more adversities
 - [ ] Add in vitro data from ToxCast and other sources
 - [ ] Add physio-chemical properties
 - [ ] Run XPaths (pheotype-to-pathway-mapping) pipeline on all phenotypes
 - [ ] Run entity linker to connect phenotypes to ontologies
 - [ ] Add compound fingerprints / graphs as node attributes
 - [ ] Add data from non-mammalian species
 - [ ] Add more chemicals (whole of Pubmed?)
 - [ ] Add PMID to relation (COMPOUND) -[r{pmid:pmid_article}]-(PHENO)
 - [ ] Connect data from cholestasis data extraction project
 - [ ] Improve CREW (see issue: #10)
 - [ ] Improve NER (see issue #11)
 - [ ] Improve Entity linker (see issue #12)
